language: python
dist: trusty
sudo: false
python:
  - 3.5
install:
  - pip install --upgrade tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
